name: master

on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Start up dependencies
        run: docker-compose up -d
      - name: Wait for dependencies to start up
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Master buld tests
        run: |
          make test   
  functional:
    name: Run functional tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start up dependencies
        run: docker-compose up -d
      - name: Wait for dependencies to start up
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
      - name: Test
        env:
          AWS_REGION: us-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          make test/functional
  build:
    needs:
      - functional
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run build & push
        run: |
          make docker/build
          make docker/push