name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.4' # The Go version to download (if necessary) and use.
      - name: Set tag
        run: echo "GITHUB_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set short sha
        run: echo "GITHUB_SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Build
        run: |
          VERSION="$GITHUB_TAG ($GITHUB_SHORT_SHA)" make build
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        run: make docker/build
      - name: Push docker image
        run: make docker/push
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/plumber-darwin
            build/plumber-linux
            build/plumber-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout homebrew-public
        uses: actions/checkout@master
        with:
          repository: batchcorp/homebrew-public
          token: ${{ secrets.ACTIONS_TOKEN }}
          path: ./homebrew
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: SHA linux
        id: shasumlinux
        run: |
          echo ::set-output name=sha::"$(shasum -a 256 ./build/plumber-linux | awk '{printf $1}')"
      - name: SHA darwin
        id: shasumdarwin
        run: |
          echo ::set-output name=sha::"$(shasum -a 256 ./build/plumber-darwin | awk '{printf $1}')"
      - name: Update plumber.rb
        run: |
          cd ./homebrew
          sed -i .old '/    sha256/ s/"[^"][^"]*"/"${{ steps.shasumdarwin.outputs.sha }}"/' plumber.rb
          sed -i .old '/      sha256/ s/"[^"][^"]*"/"${{ steps.shasumlinux.outputs.sha }}"/' plumber.rb
          sed -i .old '/    url/ s/"[^"][^"]*"/"https:\/\/github.com\/batchcorp\/plumber\/releases\/download\/{{ $GITHUB_TAG }}\/plumber-darwin"/' plumber.rb
          sed -i .old '/      url/ s/"[^"][^"]*"/"https:\/\/github.com\/batchcorp\/plumber\/releases\/download\/{{ $GITHUB_TAG }}\/plumber-linux"/' plumber.rb
          cat plumber.rb
#          git add .
#          git config user.name github-actions
#          git config user.email github-actions@github.com
#          git commit -am "Bumping release"
#          git push



